linters:
  enable:
    - revive
linters-settings:
  revive:
    rules:
      - name: if-return
        disabled: true

issues:
  include:
    - EXC0012
    - EXC0013
    - EXC0014
    - EXC0015
  exclude:
    - "don't use underscores in Go names"
