# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: Service
metadata:
  name: tradepost
spec:
  type: ClusterIP
  selector:
    app: tradepost
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tradepost
spec:
  replicas: 1 # EDIT: Number of instances of deployment
  selector:
    matchLabels:
      app: tradepost
  template:
    metadata:
      labels:
        app: tradepost
    spec:
      serviceAccountName: k8s-service-account
      containers:
      - name: tradepost-service
        image: tradepost
        ports:
          - containerPort: 80
        envFrom:
          - configMapRef:
              name: spanner-config
        env:
          - name: SERVICE_HOST
            value: "0.0.0.0"
          - name: SERVICE_PORT
            value: "80"
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
            ephemeral-storage: "100Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
            ephemeral-storage: "100Mi"
