
name: Backend Tradepost Service code tests
on:
  pull_request:
    paths:
      - 'backend_services/tradepost/**'
jobs:
  test:
    name: Tradepost Service Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.19.2'
      - name: Check go version
        run: go version
      - name: Lint files
        uses: golangci/golangci-lint-action@v3
        with:
          working-directory: ./backend_services/tradepost
          args: --timeout 120s --verbose
      - name: Run unit tests
        run: |
          make tradepost-test
      - name: Run integration tests
        run: |
          make tradepost-test-integration
