
name: Backend code tests
on:
  pull_request:
    paths:
      - 'src/**'
jobs:
  lint:
    name: Lint files
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        service: [profile, matchmaking, item, tradepost]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.19.2'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          working-directory: ./src/golang/${{matrix.service}}-service
          args: --timeout 120s --verbose
  test:
    name: Tests
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        service: [profile, matchmaking, item, tradepost]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '^1.19.2'
    - name: Check go version
      run: go version
    - name: Run unit tests
      run: |
        make ${{matrix.service}}-test
    - name: Run integration tests
      run: |
        make ${{matrix.service}}-test-integration
