on:
  push:
    branches:
    - main
  pull_request:
name: Gaming code tests
jobs:
  units:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [profile, matchmaking, item, tradepost]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '^1.18.4'
    - name: Check go version
      run: go version
    - name: Run tests
      run: |
        make ${{matrix.service}}-test
  integration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [profile, matchmaking, item, tradepost]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '^1.18.4'
    - name: Check go version
      run: go version
    - name: Run tests
      run: |
        make ${{matrix.service}}-test-integration
