
name: Microservices code tests
on:
  pull_request:
    paths:
      - 'src/**'
jobs:
  lint:
    name: Lint files
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        service: [profile, matchmaking, item, tradepost]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.18.4'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          working-directory: ./src/golang/${{matrix.service}}-service
  unit:
    name: Unit tests
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        service: [profile, matchmaking, item, tradepost]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '^1.18.4'
    - name: Check go version
      run: go version
    - name: Run tests
      run: |
        make ${{matrix.service}}-test
  integration:
    name: Integration tests
    runs-on: ubuntu-latest
    needs: [lint, unit]
    strategy:
      matrix:
        service: [profile, matchmaking, item, tradepost]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '^1.18.4'
    - name: Check go version
      run: go version
    - name: Run tests
      run: |
        make ${{matrix.service}}-test-integration
