on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Latest Release

jobs:
  release:
    name: Create Release
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.19.2'
      - name: Set binary name
        run: |
          BINARY_NAME=spanner-gaming-sample-${{github.ref_name}}.tar.gz
          echo "BINARY_NAME=$BINARY_NAME" >> $GITHUB_ENV
      - name: Build
        run: |
          make build-all
          tar -czvf "$BINARY_NAME" README.md generators/README.md generators/*.py bin/*
      - name: Release with Notes
        uses: softprops/action-gh-release@v1
        with:
          body_path: ".github/CHANGELOG.md"
          draft: true
          files: ${{env.BINARY_NAME}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
