on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Latest Release

jobs:
  lint:
    name: Lint files
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        service: [profile, matchmaking, item, tradepost]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.19.2'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          working-directory: ./backend_services/${{matrix.service}}
          args: --timeout 120s --verbose
  test:
    name: Tests
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        service: [profile, matchmaking, item, tradepost]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.19.2'
      - name: Check go version
        run: go version
      - name: Run unit tests
        run: |
          make ${{matrix.service}}-test
      - name: Run integration tests
        run: |
          make ${{matrix.service}}-test-integration
  release:
    name: Create Release
    runs-on: 'ubuntu-latest'
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.19.2'
      - name: Set binary name
        run: |
          BINARY_NAME=spanner-gaming-sample-${{github.ref_name}}.tar.gz
          echo "BINARY_NAME=$BINARY_NAME" >> $GITHUB_ENV
      - name: Build
        run: |
          make build-all
          rm workloads/.gitignore
          rm workloads/**/Dockerfile
          tar -czvf "$BINARY_NAME" README.md LICENSE workloads/* bin/*
      - name: Release Notes
        run:
          git log $(git describe HEAD~ --tags --abbrev=0)..HEAD --pretty='format:* %h %s' --no-merges > ${{ github.workspace }}-CHANGELOG.md
      - name: Release with Notes
        uses: softprops/action-gh-release@v1
        with:
          body_path: ${{ github.workspace }}-CHANGELOG.md
          draft: true
          files: ${{env.BINARY_NAME}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
